<div style="background: linear-gradient(90deg, #2c3e50, #3498db); 
            padding: 20px; border-radius: 10px; text-align:center;">
    <h1 style="color:white; font-family:Trebuchet MS, sans-serif; font-size:40px;">
        📊 Machine Learning Analysis 🚀
    </h1>
    <p style="color:#ecf0f1; font-size:26px; margin-top:10px;  text-align:center;">
         OneHotEncoder
    </p>
</div>

In [50]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [51]:
d = {'sales': [100000,222000,1000000,522000,111111,222222,1111111,20000,75000,90000,1000000,10000],
'city': ['Tampa','Tampa','Orlando','Jacksonville','Miami','Jacksonville','Miami','Miami','Orlando','Orlando','Orlando','Orlando'],
'size': ['Small', 'Medium','Large','Large','Small','Medium','Large','Small','Medium','Medium','Medium','Small',]}

In [52]:
df = pd.DataFrame(data = d)

In [53]:
df.head().style.background_gradient(cmap="coolwarm")

In [54]:
from sklearn.preprocessing import OneHotEncoder

In [55]:
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False).set_output(transform="pandas")

In [56]:
ohetransform = ohe.fit_transform(df[['size']])

In [57]:
ohetransform

    size_Large  size_Medium  size_Small
0          0.0          0.0         1.0
1          0.0          1.0         0.0
2          1.0          0.0         0.0
3          1.0          0.0         0.0
4          0.0          0.0         1.0
5          0.0          1.0         0.0
6          1.0          0.0         0.0
7          0.0          0.0         1.0
8          0.0          1.0         0.0
9          0.0          1.0         0.0
10         0.0          1.0         0.0
11         0.0          0.0         1.0

In [58]:
df = pd.concat([df, ohetransform], axis=1).drop(columns=["size"], errors="ignore")

In [59]:
df

      sales          city  size_Large  size_Medium  size_Small
0    100000         Tampa         0.0          0.0         1.0
1    222000         Tampa         0.0          1.0         0.0
2   1000000       Orlando         1.0          0.0         0.0
3    522000  Jacksonville         1.0          0.0         0.0
4    111111         Miami         0.0          0.0         1.0
5    222222  Jacksonville         0.0          1.0         0.0
6   1111111         Miami         1.0          0.0         0.0
7     20000         Miami         0.0          0.0         1.0
8     75000       Orlando         0.0          1.0         0.0
9     90000       Orlando         0.0          1.0         0.0
10  1000000       Orlando         0.0          1.0         0.0
11    10000       Orlando         0.0          0.0         1.0

<div style="background-color:#f9f9f9; border-top:6px solid #3498db; 
            padding:20px; border-radius:8px; text-align:center; margin-top:40px;">
    <h2 style="color:#2c3e50; font-family:Arial, sans-serif;">
        ✅ End of Notebook
    </h2>
    <p style="font-size:16px; color:#34495e; text-align:center;"">
        Thank you for reviewing this analysis.<br>
        🚀 Keep experimenting, keep learning!
    </p>
</div>